### PR TITLE
Made sure download function in client could download all desired image types.

### PR DESCRIPTION
**Pull request by jbilskie**
".png", "jpg", ".tiff"

".png" defaults

### CODE REVIEW

**Comment by jbilskie** [comment]
@kevinmchu I didn't touch the tests or unzip functions but now I get a pytest fail for test_unzip... any idea why?

**Comment by kevinmchu** [comment]
Do you have a jpg file in test-unzip2.zip?

**Comment by jbilskie** [comment]
Yeah its the same one I pulled from the master branch.

**Comment by kevinmchu** [comment]
The test that fails worked on my computer. I think that problem is that the zip files I created for the `test_unzip` function are compatible with Mac but not Windows. Are there any other files in test-unzip2.zip?

**Comment by jbilskie** [comment]
In test-image I have to folders 1)_MACOSX and 2) test-unzip2
_MACOSX has one folder under it test-unzip2 which has ._test1.jpg
test-unzip2 then has test1.jpg

**Comment by kevinmchu** [comment]
I'll switch over to Bootcamp and make the zip file there to see if that makes a difference.

**Comment by kevinmchu** [comment]
I uploaded a new version of test-unzip2.zip to the master branch. Let me know if this works.

**Pull request closed without merging**
