### PR TITLE
Initial commit for client unit tests. (Retry)

### PR DESCRIPTION
**Pull request by jbilskie**

### CODE REVIEW

**Comment by jbilskie** [comment]
@dward2 Locally, I don't get any pytest errors, but for some reason I'm now getting:

ImportError while importing test module '/home/travis/build/jbilskie/BME547_final/test_gui.py'.
Hint: make sure your test modules/packages have valid Python names.

for both the test_gui.py and test_server.py which have zero changes in this pull request... Do you have any idea what I need to fix.

**Comment by dward2** [comment]
@jbilskie When I try to run your tests on my computer, I am getting the same errors as Travis.  Let me take a look.  Out of curiosity, is your computer running macOS or Windows?

**Comment by dward2** [comment]
@jbilskie I have a hypothesis:  there may be differences between the module versions that Travis (and maybe I) is using in its virtual environment compared to what you have on  your computer.

Would you do this for me, please.  On your local computer, how are you running python and pytest?  Are you using PyCharm?  Conda?  A Terminal window?  What I would like for you to do is run the following command from a terminal window with your virtual environment active:  `pip freeze > daw.txt`.  This should create a file called `daw.txt` in your project folder.  Please either commit that to your repository so I can see it, or e-mail it to me.  This file will list the specific version you have installed in your personal virtual environment and we can compare that against what is in Travis.

Or, if you want to try something, take the `daw.txt` file and commit it to your branch.  Then, modify the `.travis.yml` file to say `-pip install -r daw.txt`.  This will ask Travis to create a Virtual environment identical to that on your computer.

**Comment by dward2** [comment]
@jbilskie Thanks.  I was just looking at your error more closely, and yours is failing because it is having trouble importing `TkAgg` backend related to matplotlib.  This was an issue we looked at before in issue #52 .  I'm going to review the <https://matplotlib.org/faq/usage_faq.html#what-is-a-backend> website.

**Comment by jbilskie** [comment]
@dward2 I am running Windows, and I run python scripts in windows command prompts by typing 'python file.py'. I run pytest in the command prompt by typing 'pytest -v --pep8'. 

I created the daw.txt file and then tried updating the .travis.yml file as suggested. I still get the same error once pushed to Github, but have no pytest errors locally still.

I remember that issue, but don't understand what has changed with this commit because I wasn't having that problem earlier.

**Comment by dward2** [comment]
@jbilskie Try this.  Line 12 in `gui.py` that I show below:

https://github.com/jbilskie/BME547_final/blob/8d4d10413951715de30cbe1240efc694edfd33df/gui.py#L12

Delete this line and then try Travis.

**Comment by dward2** [comment]
@jbilskie Okay, I see that worked.  The question now is, does removing that line cause other problems?  Will it run on your computer without the line?  I believe one of your teammates has a Mac?  Does it run on their without it?

**Comment by jbilskie** [comment]
Everything works for me. @xc130 do you need line 12 in gui.py ('matplotlib.use("TkAgg") to make things work on Mac?

**Comment by dward2** [comment]
@jbilskie @xc130 If that line is needed for the Mac, it is okay to take that line in/out as needed based on the platform.  There is probably even a sophisticated way for Python to check the operating system and either execute or not execute based on the operating system, but that may require some research.  Manual removal/addition is fine for now.  I'm signing off for the night.  If anything else comes up, go ahead and post an issue/comment, and I'll check on it tomorrow.

**Comment by jbilskie** [comment]
Thank you @dward2 !

**Comment by xinlin-chen** [comment]
From what I remember, I used that line because I had problems displaying or plotting histograms without selecting a GUI backend

**Pull request merged**
