### PR TITLE
Kmc/test server2

### PR DESCRIPTION
**Pull request by kevinmchu**

### CODE REVIEW

**Comment by kevinmchu** [comment]
Finished writing tests in `test_process_image_download`. There was no exception problem in `exist_input`, the bug was in `test_process_image_download` (which is now fixed).

**Comment by kevinmchu** [comment]
@dward2 All the tests in the kmc/test_server2 branch passed on my computer, but some of them are failing in Travis. Why could this be the case?

**Comment by dward2** [comment]
@kevinmchu The kmc/test_server2 branch also passes all of its tests on my computer.  If you try to do the merge a second time, do the same tests in Travis give the error?  Or, does the test that errors change each time?

**Comment by dward2** [comment]
@kevinmchu Well, I'm not sure what happened, but I was trying some things in your repo and somehow one of the builds for this pull request was restarted and it passed.  So, I manually restarted the other one and it also passed.  So, my only guess is that perhaps with doing some database access from Travis, there might be some slow response times that causes some issues and occasional failed tests.  So, rerunning might yield a time where there aren't those problems?  So, what I can suggest is that when they pass on your computer, and then fail on Travis, try rerunning them in Travis.  Look for a "restart build" button, or a re-run link somewhere on the various Travis pages.

**Comment by kevinmchu** [comment]
@dward2 Interesting. Thank you for the insight.

**Pull request merged**
